"""Weight classes enum"""

from enum import Enum
class WeightClass(Enum):
    """Weight classes enum"""
    HEAVYWEIGHT = 1
    CRUISERWEIGHT = 2
    LIGHTHEAVYWEIGHT = 3
    SUPERMIDDLEWEIGHT = 4
    MIDDLEWEIGHT = 5
    SUPERWELTERWEIGHT = 6
    WELTERWEIGHT = 7
    SUPERLIGHTWEIGHT = 8
    LIGHTWEIGHT = 9
    SUPERFEATHERWEIGHT = 10
    FEATHERWEIGHT = 11
    SUPERBANTAMWEIGHT = 12
    BANTAMWEIGHT = 13
    SUPERFLYWEIGHT = 14
    FLYWEIGHT = 15
    LIGHTFLYWEIGHT = 16
    MINIMUMWEIGHT = 17
    LIGHTMINIMUMWEIGHT = 18