"""empty message

Revision ID: a12ea5615013
Revises: 
Create Date: 2018-01-07 17:48:06.718097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12ea5615013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attack', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attack', 'fighter', ['fighter_id'], ['id'])
    op.add_column('defence', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'defence', 'fighter', ['fighter_id'], ['id'])
    op.add_column('fight', sa.Column('result', sa.Integer(), nullable=False))
    op.add_column('fight', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.add_column('forbidden', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'forbidden', 'fighter', ['fighter_id'], ['id'])
    op.add_column('maneuver', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'maneuver', 'fighter', ['fighter_id'], ['id'])
    op.add_column('missed', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'missed', 'fighter', ['fighter_id'], ['id'])
    op.add_column('trick', sa.Column('fighter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trick', 'fighter', ['fighter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trick', type_='foreignkey')
    op.drop_column('trick', 'fighter_id')
    op.drop_constraint(None, 'missed', type_='foreignkey')
    op.drop_column('missed', 'fighter_id')
    op.drop_constraint(None, 'maneuver', type_='foreignkey')
    op.drop_column('maneuver', 'fighter_id')
    op.drop_constraint(None, 'forbidden', type_='foreignkey')
    op.drop_column('forbidden', 'fighter_id')
    op.drop_column('fight', 'winner_id')
    op.drop_column('fight', 'result')
    op.drop_constraint(None, 'defence', type_='foreignkey')
    op.drop_column('defence', 'fighter_id')
    op.drop_constraint(None, 'attack', type_='foreignkey')
    op.drop_column('attack', 'fighter_id')
    # ### end Alembic commands ###
